[package]
name = "mothbus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.11"
axum-macros = "0.2.3"
color-eyre = "0.6.1"
handlebars = "4.3.1"
http = "0.2.8"
serde = { version = "1.0.138", features = ["derive"] }
tokio = { version = "1.19.2", features = ["full"] }
toml = "0.5.9"
tower-http = { version = "0.3.4", features = ["full"] }
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
